bst.cpp
dfs.cpp

Implemented the Binary Search Tree

Added the Binary Search Tree Algorithm

---

prim.cpp

Prim’s Minimum Spanning Tree (MST)  Implementation

Prim’s Minimum Spanning Tree (MST)

---

Sorting Algorithms/radix_sort.cpp

I added radix sort algorithm in a folder named sorting algorithm , Please review it.  Thank YOu

Added Radix sort algorithm

---

DP/Coin_Combination1.cpp
DP/Coin_Combination2.cpp
DP/Dice_Combinations.cpp
DP/Minimizing_Coin.cpp
DP/Money_Sums.cpp
DP/README.md
DP/arrayDescription.cpp
DP/bookShop.cpp
DP/editDistance.cpp
DP/gridPaths.cpp
DP/projects.cpp
DP/rectangleCutting.cpp
DP/removalGame.cpp
DP/removingDigits.cpp
DP/twoSets2.cpp

__28__
Added folder DP which contains solution to the standard DP  problems from CSES problem set
https://cses.fi/problemset/list

added solutions for DP problems

---

DP/README.md

Added link to all the problems

---

Trees Algorithm/binary_tree_traversal_inorder.cpp
Trees Algorithm/binary_tree_traversal_postorder.cpp
Trees Algorithm/binary_tree_traversal_preorder.cpp

Inorder traversal added. Will be adding more traversals too. Pls check @siddharth25pandey .

added inorder tree traversal

---

Trees Algorithm/LCA_of_BinaryTree.cpp

LCA_of_BinaryTree is one of the frequently asked question for SDE role.
LCA stands for Lowest Common Ancestor.
Comments have been added for better understanding.

LCA_of_BinaryTree

---

Trees Algorithm/check_if_BinaryTree_a_BST.cpp

Given code will tell if a binary tree is BST or not.
comments have been added for better understanding.

check_if_BinaryTree_a_BST

---

Trees Algorithm/LCA_of_BST.cpp

LCA_of_BST is a good and frequently asked question in interviews for SDE-1 role.
Comments have been added for better understanding.

LCA_of_BST

---

Trees Algorithm/Red_Black_Tree.cpp

Better code for red black tree

Red Black Tree

---

MinJumps_DP.cpp

Added a Min Jumps DP problem pls review and merge it @siddharth25pandey

Added Min Jumps DP problem 

---

DP/MinJumps_DP.cpp

Added the Min_Jumps DP Prog in the DP folder pls review and merge :)

Added the Min_Jumps DP Prog

---

Graph Algorithm/FloydWarshallAlgorithm.cpp
Graph Algorithm/KruskalAlgorithm.cpp.cpp

Hey,I have added  FloydWarshall Algorithm and Kruskal Algorithm...If u like it  you can merge it as well as accept my PR

Added FloydWarshall Algorithm and Kruskal Algorithm

---

Searching Algo/exponential_search.cpp
Searching Algo/interpolation_search.cpp
Searching Algo/jump_search.cpp

1.Jump-Search algorithm is searching algorithm for sorted array.
Its check fewer element by jumping by fixed number.
2.Exponential Search algorithm is searching algorithm as well.
size of search increase by power of 2 eg-2^0,2^1 etc and if , no element found till last element search size will start
reducing backward.
3.Interpolation Search is an algorithm for searching for a key in an array that has been ordered by numerical values assigned to the keys.

Jump-Search,Exponential Search,Interpolation Search

---

Sorting Algorithms/CountingSort.cpp

Contributing with Counting Sort, for it was not in the Repo.

Counting Sort

---

Sorting Algorithms/IntrospectiveSort.cpp

Introspective or Introspec Sort

Introspective Sort

---

Graph Algorithm/Bipartite_Graph.cpp

Added a code for checking whether the graph is bipartite or not, using DFS algorithm.
Hacktoberfest 2021

added Bipartite graph check

---

Linked List Algo/move element to start in linked list.cpp

added new linked list algorithm

Added new linked list algorithm

---

Linked List Algo/Nth_node_from_the_end.cpp

added a new linked list program

added a new linked list program

---

DP/LongestCommonSubsequence.cpp

Added Solution for Longest Common Subsequence in C++ under DP folder.

Nikhil-1503| LongestCommonSubsequence.cpp| Added Solution

---

bit_manipulation/binary_and_operator.cpp
bit_manipulation/binary_compliment_operator.cpp
bit_manipulation/binary_or_operator.cpp
bit_manipulation/binary_shifts.cpp
bit_manipulation/binary_xor_operator.cpp

I have made some c++ programs on bit manipulation. This contains some basic operations with examples

Bit manipulation

---

Stack Algorithims/Two_Stacks_in_one_array.cpp

Sir, I have added the source code of Implementation of 2 stacks in one array on Stack Algorithms folder
Thank you

Implementation of 2 stacks in 1 array | Added source code

---

Recursion/towerOfHanoi.cpp

Added a new folder named Recursion and then added the Tower Of Hanoi cpp file in it.

Anirudh | Recursion/towerOfHanoi.cpp | Added a file

---

Queue Algorithm/sliding_window_max_of_all_subarrays.cpp

This code will find the maximum elements in all sub-arrays of size 'k' in an array. 
Double-ended Queue data structure is implemented here using CPP STL.

Created sliding_window_max_of_all_subarrays.cpp

---

Graph Algorithm/Cycle Detection in Directed Graph using BFS(Kahn's Algorithm).cpp

I have added Kahn's Algorithm in Graph Folder

Create Cycle Detection in Directed Graph using BFS(Kahn's Algorithm).cpp

---

DP/LCIS(LCS+LIS).cpp

Created **_Longest Common Increasing Sub-Sequence_** which is the combination of
**_Longest Common Sub-Sequence and Longest Increasing Sub-Sequence_**

Created LCIS(LCS+LIS).cpp

---

Searching Algo/kth smallest element.cpp

Searching the kth smallest element in the least complexity of time and space.
[Hacktoberfest contribution]

Searching the kth smallest element

---

Trees Algorithm/StructurallyIdentical.cpp

C++ Implementation to find whether 2 binary trees are structurally identical or not.
Hacktoberfest 2021.

add structurally identical binary trees check

---

Maths/smallest_prime_factor.cpp

Please review it and merge as a part of Hacktoberfest 2021

Added New Code in Math Folder

---

Graph Algorithm/Kahn's algorithm.cpp
Graph Algorithm/Kahn’s Topological Sort Algorithm.cpp

I have Added 2 files for kahn's algorithm #233.
one is direct kahn's algorithm with its direct function and the other file is Kahn's algorithm with topological sorting.

I have Added 2 files for kahn's algorithm #233

---

Searching Algo/MaxDifferenceInArray.cpp

This is a PR for Hacktoberfest 2022

Added MaxDifferenceInArray.cpp

---

Recursion/Palindrome_Check_using _Recursion.cpp

please add hactoberfest accepted label

Ashutosh Shukla | Recursion | Added Palindrome Check using Recursion

---

Searching Algo/missing_number_in_array.cpp

Signed-off-by: rithwik003 <amaraneni.rithwik@gmail.com>

Added missing_number_in_array.cpp

---

Binary Search/Search_in_2d_matrix.cpp

Added the classical binary search problem of searching in a 2-d matrix

Search in a 2d matrix

---

strings/KMP algorithm.cpp
strings/Minimum characters to be added at front to make string palindrome__ON KMP ALGORITHM.cpp

Hey I have added KMP algorithm with one question on this algorithm

KMP ALGORIHTM  ADDED

---

DP - LEETCODE/RunningSum1D.cpp

This is my PR for Hacktoberfest 2022

Added Running Sum in 1D Array problem

---

Stack Algorithims/PostfixToInfix.cpp

this is a pr for hacktoberfest 2022

Added Postfix to infix conversion using Stack

---

Arrays/productofArray_exceptSelf

hi, I added code for Product of Array except Self .

added Product of Array Except Self

---

strings/LongestCommonPrefix.cpp

Created LongestCommonPrefix.cpp

Kushagra |  LongestCommonPrefix.cpp

---

Linked List Algo/ReverseLinkedList.cpp
Linked List Algo/insertAtTail.cpp
Linked List Algo/insertAthead.cpp
Linked List Algo/kReverse.cpp
Linked List Algo/lenghOfLinkedList.cpp

I have added some problem and solution . you can review once and merge. And I will add more problems in linked list.

Added more problems and solution in Linked list

---

Arrays/subarray with given sum.cpp

I have added a c++ program named subarray with given sum. Kindly merge it.

Create subarray with given sum.cpp

---

Binary Search/The painter’s partition problem.cpp

Create The painter’s partition problem.cpp

---

.vscode/settings.json
DP/reverseArray.cpp

reverse array

---

Arrays/merge_2_sorted_arrays.cpp

added merging of 2 sorted arrays

---

Arrays/Kadane's  Algorithm.cpp

I have added a c++ program named Kadane's Algorithm. please review and merge it. Thank You.

Create Kadane's  Algorithm.cpp

---

strings/reverse word in a given string.cpp

I have written a code in c++ named Reverse words in a given string. Kindly review and Merge it please.

Create reverse word in a given string.cpp

---

Leetcode/Find Minimum in Rotated Sorted Array.cpp

Question Link: https://leetcode.com/problems/find-minimum-in-rotated-sorted-array/

Create Find Minimum in Rotated Sorted Array.cpp

---

DP - LEETCODE/Paths in matrix whose sum is divisible by k.cpp

Paths in matrix whose sum is divisible by k is added to the Leetcode DP folder

added 3d dp question

---

DP - LEETCODE/TwoSum_IV_Input_is_a_BST.cpp

Signed-off-by: Umesh Chandra <umesh.sakinala20@gmail.com>

Added Two Sum IV - Input is a BST using CPP

---

Graph Algorithm/Water_jug.cpp

I have added the code for Water Jug problem in C++ and added it in the Graph folder
Please merge my pull request under the label **Hacktoberfest** @siddharth25pandey

Added the new file for the Water Jug program in C++

---

DP - LEETCODE/MaxSubArraySum.cpp

An important leetcode problem which has been asked in many competitive exams as well as interview questions. Please accept my pull request on priority as I am still at 0 PR in hactober fest.

MaxSubArraySum.cpp : A leetcode solution

---

DP - LEETCODE/BreakaPalindrome.cpp

please accept my pull request on priority as I am still at 0PR in HactoberFest.

BreakaPalindrome.cpp

---

DP/longest_increasing_subsequence.cpp

longest_increasing_subsequence_DP(solution) with clean code .. Thank You !!
#hacktoberfest2022

longest_increasing_subsequence_DP

---

Backtrack/Combination_Sum.cpp

Combination sum solved with the help of backtracking.

Code for Combination Sum

---

Leetcode/Palindrome Number.cpp

Question Link 
https://leetcode.com/problems/palindrome-number/description/

Create Palindrome Number.cpp

---

DP - LEETCODE/Largest_Perimeter_Triangle.cpp

Signed-off-by: Umesh Chandra <umesh.sakinala20@gmail.com>

Added Largest Perimeter Triangle using CPP

---

Recursion/Generate_Parentheses.cpp

It takes a number and returns the different possible valid combinations of parenthesis using that number of brackets.

Added Valid Parenthesis generator code

---

C++ Pattern problem/Butterflypattern.cpp

I hope this helps your repository

Added butterfly pattern

---

Arrays/Minimum_swaps_to_sortArray.cpp
strings/Multiply_two_large_number.cpp

I have done cpp program for multiplication of two strings.
I think it is complete to merge in string folder.
Please Have a look.

Added file for problem multiply two strings

---

DP/0-1_knapsack.cpp

I have solved 0-1 knapsack problem for DP Section
Please, have a look

Added file of 0-1_knapsack.cpp for DP Section

---

strings/sum_of_two_large_numbers.cpp

Added string code to calculate the sum of two large numbers. In case of using int data type, there will be an overflow so string approach.

Added string code

---

Binary Search/BinarySearchonLinkedList.cpp

Added sample code for using binary  search on a singly linked list.

Payonidhi|BinarySearchonLinkedList|

---

Trees Algorithm/BFS.cpp
Trees Algorithm/DFS.cpp
Trees Algorithm/Minimum_Spanning_Tree.cpp

please review and merge it. In future add more problems.

Added Trees algorithms

---

Sorting Algorithms/CoctailSort.cpp

I have included cocktail sort with the execution time taken to sort it.

Cocktail Sort

---

DP/Burst Balloons.cpp

Pull request for hacktoberfest

Create Burst Balloons.cpp

---

DP/Palindrome_Partitioning_ II.cpp

Create  Palindrome_Partitioning_ II.cpp

---

Graph Algorithm/codechef_chess_knight_move.cpp

Thank you for reading my pull request please add my contribution to your repository. the link for codechef problem chess knight move is attached.
https://www.codechef.com/problems/PRGCUP01

Added a codechef graph problem chess knight move

---

C++ Pattern problem/PascalTriangle.cpp
cpp-website/package-lock.json
cpp-website/package.json
cpp-website/src/components/Contactus.js
cpp-website/src/components/contactus.css

anubhav soni changes done in contact us page in the cpp-website

anubhav soni changes done in contact us page in the cpp-website

---

Arrays/spiral_matrices.cpp

iI added an important ques to clear 2d matrices topic

added spiralmatrix file

---

C++ Pattern problem/diamond_pattern.cpp

hi i want to add diamond pattern using c++ in your repo please merge this pr in your repo under hactoberfeest 2022

added diamond pattern
